# Generated by Django 4.2.3 on 2023-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fae', '0002_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologies',
            name='myimg',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
