# Generated by Django 4.2.3 on 2023-10-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fae', '0003_technologies_myimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mpn', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
        migrations.DeleteModel(
            name='Blocks',
        ),
        migrations.DeleteModel(
            name='Technologies',
        ),
    ]
